apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QtYk+Lt2yIxy9/3pvST5UQZj4fpC/95tqTJg8z2n0Ir+smxltbCtksc2rwtT3pgFUbs4UMfu3rJH+KigRH4TLubfjNvypdaNRSlm3UiAhUCAGV6L+KRvKnI4KglI25zsJd0ST2byeowO2X2OMaX4aYvPZHKydT4bysSl/pIVUwoPVr/yY104VfgblT4wEYPxPsQQOuZRmXhjXpn2HB8dKlqm5onpGwP6l+EXWSSSR0hNK0xx7yz8nHk21VveoJHKEVejUy+31lEndJdY5aPCbEKUuXsHktPxNTZlpdJumfKFR6TMfkWEdLdQih6dOrhh8NWL13ottNjLbkd3phL505NgEx6JhGvsPajhDsosn8dfFF0NTPXeC7G2xAhFc+J6,iv:2FHzvza1KKtzhGmGYqA9aA6j15DPaVdd+kg0yJA3xDk=,tag:oSWJjXNUKbFL/ythjXZVEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:94xsx1TL0HWUgsbf4mMUUajV5nKVMBY4etyqOl1q3AF8hvCUVLH59eNPWdMg2RwkYpShUPX5Ng5EcOLiByo/w1CLz/A5eEZOQPeTPFz1U8nYMFd00fXBAou6cs7VKZa9rAjf1O+IbNJkECpsBwbpsXLz6oKQ8Ugz8FXin9BqGRr0PBI98UiFb+Gz2EQFr/vTfEJvl30LAnWDafBKSmb3dmzu57CUiy2pbdTec4hUbv9H4t8Xb7AJJhN9ei+9ZJOmOkX8o0foBxDk3ZzMog==,iv:7+QIEHCnWI91ds6n4ky4VgCFhdG+t2SapIU2ARBnz64=,tag:H8kHo0ZGGUGSWf/QdzWt/g==,type:str]
    known_hosts: ENC[AES256_GCM,data:qqBB44F8jtGMMc5XojpvTAy/cBtzNuzbTXvVpYGogoTBOoPylwGZtqH3cQ/EHRWu8q/Qymx6MyNkbmqUU1CyugHCkXyzraepDrqLSm1wMZtkYy9Nalnbrrte1RmKRW30MKcw2VSN1T+xGy4b0OOjSFb42uItUBjwfVNm1WrT/KqwZF7oJktcGjxWGXIuN/PmZmb2jhtHukjLdLhttdCU+Ft+KuSjdtlQrebz,iv:6B8RirLyAPZfUUcoum9nDSsEOH7rJexygbxycqIugHo=,tag:nmsqItWmaudFfdjLTHH/fA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dh500hvzwf3pzyk3hmye4580nn8dme6tu5mtjag5kr45ad5cw3jq04uw5a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OWJla3Y4TkNsenA4TURZ
            c3F2ZUlQbUx5aXBOcUtPZ0VjVUI5Y2wxdzFzCjk0VEY4ejVjL0liMUtNY0h4TFhX
            dGdpU055ejRjNG1BK3RnZllKSDl3b0kKLS0tIENxaU10NTFhdTg0cG81QURZWHhM
            UTZSMEk0dStpRU5nbEVCcmFWK1NTSGMKNwrPdp4iewi9Z2F3w4j45lL43Eb+I4ey
            sldq7RV3vodHjE470mNz2uMTZD27jz12Anoryp69dqjqrs363LErbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T01:04:53Z"
    mac: ENC[AES256_GCM,data:0YxOPVpMrercxZuLVnt6NQ/56yjHIZR8mjKmm70LCdCAD5iNRq42MCflEBvEjwDAgPPr2b+by4RrbiY1VQ6fJUgt85DS+DWxBD/RTOHXalNVVoKhj4wqhEKpj0k0XGqZZczTST3xLuV9rGaU95rjIkqd4zeolvcknHyvNqf0v2c=,iv:qmCKt/fCjcG6dCEw2rZ4gZQxIIfQ7R4/CtPgq+Ix6Ag=,tag:MdnjlG/FNswj/K/uDPygiw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
