apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nUBcxmxW+vxW5xqXpVZY27RC/C9yYh2tRc6apxT+dr7vvp1SwAFIpevqpLq8hTsirS8+xA91U8x/PveKsOVjMgpEN99H5T2ziukP+RqeTdeig0/c/uxmwxWL5pdqtFiN6VY1vgDNhOCJXknxX3r3E43h41uQzXd98wPP180SZmbH+TJhxJJSjTcIJSCOwFyhKsZiLdnuVHNBbwtwpjMIyoqpnVV6w6Fjkq4sM0hatFn1wMRaQf9DtMuBcvN4hbugo/iLBPHlrlcTEwES4uCJ+16kAnUvFhVf4WkCREpkbW7gBPRfU7lEmATgdNWywXFjxzAUpuXCAYj0dTV/CXVmtMP1254j4oZQpGjw+3zv2n1dUdcwJIDJpBsuuJPn5V3L,iv:fJwKMbXrjnV96l038xgcRyW7wQ9aTrai8HnobhrzxgY=,tag:Z9M7n9NdbLSUtoc06wUjng==,type:str]
    identity.pub: ENC[AES256_GCM,data:y68MIeTAL413dUuJ8KPa3eljYIuOU0T8HRy1oy9LSg7ObPY8uHi1WFJOAahkcPIa5LhwkbqCsZv+MzPUjmrmWHTp60tAjyZA1w1WexAdw2NU/A8XUaLSnExflLm29wKNnO+q/pbq1eIpc0i5TyChQB6JlzpolkKEnyNBNRP41JOwTfDX54ipxUsqiTNQjI1IpzOeWQ8nhoRae6TMPYbhSV6BQfDjNnNncWfUXlJCSdwfDf5ZQv+fKjSba8lOCyoa5G9KC3MkWLYVWFMTpw==,iv:EBdXnXC0i6eiFPywMvRXSTPfCpS/akWYekXCdK7eWeQ=,tag:3AOcbWz0VJe2cZE6zspQ8g==,type:str]
    known_hosts: ENC[AES256_GCM,data:1kDmLMLTcLp1lpQ5hqBJfJT8ARWhOmaN07Dn3Cw0Aoodp42T6k19CWC8EY6QY5U4q5hn4wx+ahMY3EyWuiC+P2XiJduQaXcW0WossR6jdUUz4G+M+gi0WqkoUvrjvIwXKkSa4FzysESKvRyoDOWvFvSvOLrqqaEce8obMAvPgcwaxE6+zDfCyEAHzhm+m3SqHc41y1/JZHXpapxyaYILkBJhZIBBNxvPGw3Z,iv:ALSpWAtW1eL3TiypnahtYpG0zI7/7R4o5V96cdC2a9w=,tag:CgJzxG+t1kvKQ1kDUCTtdg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dh500hvzwf3pzyk3hmye4580nn8dme6tu5mtjag5kr45ad5cw3jq04uw5a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bWx0aGl4QW92NFIwc0o4
            V3c2KzRtUFhOM2w2RUNQNG51anVxYkpoeGk4CnBpa3F3WE1TUzdob1JrOWkycml1
            RlJ6ckJtTFdweDNjZkhBUXVYdHNMSVEKLS0tIE5zaFJMM0dHbHVQQ2JaT1NrZzl6
            RHlMZldLUzVRNWgzN2JhOUs4c2NBN2MKdXxsYpdt+zpBKMSj5bHFB/KgtvGfRSZr
            JRYiI8vsFhvfyw3j5fTmmlTwe8tPOxy37nfkAsyLQPH8bIMmHFMWlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T02:55:44Z"
    mac: ENC[AES256_GCM,data:EB1xObJFDb6l7/dtRsoIYDN+sGOrJ4foiIQjQlsxS0LCKnSvLB3lhgve9Up4kEzmrkew/IduvjK45TemCAR5BKPaeO90+VHVHXl9D9raFSvxYkqXTE5Yb3LnGYu53v1qfp/RoN+lT49mHksCPFrtq/+AAzQRyYRaaFvf21eWMdY=,iv:QgQOlGmvv8L3fRIiD8NplxKLKl2+p6HjGYDcEDHoo8A=,tag:8mZNBseTNfFt5moNjV4M4A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
