apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZLVNVnLT9I77LjdWRUAJGgEjemqgcKahfqxZJzD6vFUf2Uiik+6EEuCZyr4h7j/JxLPbIBwbu5AkFY4UYWiiNDH22El69wv9EvPd+b7mVFPV+jNnDOUYzt80MkLNecwF4Q5Sswc45X9uEbLyRuBPLTO4USD3YkD44S2xyYpFaXtNG9tizhv10t5XsXwuTpyrzK/r6oqE+T3X9vM2KR75+caD7duSc7q9OgH13m8NtXECOCbHoUxHfve2Qii9aTqhjOxj6YeFy/TkiT9exiaCs3zFBi7ITV5/eWHivbP0E2PPksr1lkdbsC/TZ2I6tCJ/8YqLx2Jm4n8efmNg+nhr+fLYLQLBH3fSFxINlbAgSmFiRheQkKCV96iAiHzt2G6e,iv:MNYJDv9OOhPLVg9QvDOvtTqxciLSRMpQkWOF3u2POTE=,tag:uZKv5XkjBxEAvvPH+X/G3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:vZWdHloeZirHwy3PIUnMWdYH4mcypNWIMqYEgQ/fBeVf3qLXVzzC3nEmoTTL6ZulF3OKmxTZ4djO0NgkD6ZzK7TobYLURsgxoeGUi7Nnplp32XHXIvu8v0rr/OqXDUVNIl7+GcY8uS562PqcMgXqyVEhDri0SsxwsSi5dMDnsWY4GSKQRszPBxjvWYWIqeuWYG5RNGxe5al2cq1qJZS1aI3MIQkRiVV70YPyXaB12+uOxaWaK5uRU3+dkMaxPrb97OOu9uq/47E/Kgy5gw==,iv:HHb712yST883TxAhVdmpyxs8IqEkfvzQLBDAslVPc/c=,tag:6ViDtstKRlPPq8PtYNeUzg==,type:str]
    known_hosts: ENC[AES256_GCM,data:QI51ovLVuGLXdhRdgURkrlhqKROBUBidQDubR5j8c/hOIMl8RKsc6dBu0psesl//X5NIWQOS9OkniYy7tjpvA+41yfL62so261YFc3IJWHgIwFq+b/b7gNSFPVITfSSHVSmp556lIuqxzCpVTWsKjKt4wUeA4CGd+KRk4d8vT0gNseuY2PxWnIsB6nIt72S801M+akPs66MjDY4QHkqVuBph4ysUmJN2Uj46,iv:mxSyNc2bsrTHmcV0bO9UClGgE3+hUE3Nz0LQzaDsFx8=,tag:x170b5qgb6UFqnwrwo1YsA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dh500hvzwf3pzyk3hmye4580nn8dme6tu5mtjag5kr45ad5cw3jq04uw5a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVktRdS8rMmVtd3lUTUZr
            aU5CdE0wOWtpK0xJcjFha2V2cUEwRDQ2eUNFCkRnaHNxai94YkZsd1dKTHdPR0Zj
            bWl0dGhleXVnOWQvemVuSmVLdTNtNDQKLS0tIGZMUWE0QnJjeVBDNGlWZXl3VUVo
            TjBnelBJQ2hmeDZkeUNSRDJKa0ZZQW8K1wMbpEUalCVxyeN3dQLmzYyYrhFtJ2I5
            xJof+R6eKmtDryx8/8bmKipyXfhlzX9LHyqJ9EOUvUYrtNi8++iCqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T21:13:38Z"
    mac: ENC[AES256_GCM,data:a8qoE6VZ+Jxjr6ktfAyMN+bXWOrwJHxTbuGte/yT45VZ/YR6O2+YZ/+I3n76ulMnIhBR4jf6t920bQUq76oDqamb7JdgzGeokWfEG/mycfl7fbDx2YJEis+rMwpODtvV7I2biSjjWwAAVyTIXiroeaWe2msQQjTx4CVEZEiJcIM=,iv:NUvwZkze4LKE5jPkwnZbSsNK0jFOeI2Yv+7cZ+XQVKs=,tag:EHN0W62BAcPr4P2lDLC2eA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
