apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uJLcTtTLCzbQm+e0qDiuI0PKMz+plOPcBzUiHGru0xco7mysD2RBzOsG3xg2XHeK9duX6/Hy1Icbbedarq7eh7QIsht5oRAWJrbDj8ghL28EiyJmzrUH69BIxB8Rz4HpfBFZ49XF4rRnB6N38efMrtJEyS+6eecKTeWTSVU1fd9lPtJxxkmeSnl7te8ydPKSL9QKt0bEPP4j20RCGUvYBNhYUh23/T3Km0XmWuhKMXFP+bnzFRZ4HH2fEg1tdFuAr+19y7CNCqgbFORoSDcUvF64Zgb2XMVRP2KTd72nyJ9sCYpPIdsDEMTtClK2tbgqhwY2XNWJrliu/niUw22gJUSbu8WSj/KrbsMNZWs1aYQQFaWuyBPkiIT0oP4Gitjr,iv:yJVEvRPP2+/bOvgV/D2z6uepH1pflDoAaLGTjkCr2tI=,tag:sTJfKGVSitGWlOpcgTU2Uw==,type:str]
    identity.pub: ENC[AES256_GCM,data:njo5fMwqZElgvJ5LWFYy8M/a6zT/bAJB771jZoCXitKGWO1Z/Qr20yFHA4sbVQ5I4Rv2FaYbCunQ2Ue5BCO1zmt06MKPkw7AGHGNsl4FpjT+f8S8Dczcl4iZXV0tL0Ou0WlJW0us8zaeCWAc0RxYQHXoM2y+HosJ7beqibIZ1b0SslgprLqQGgGphle2J8lZvl3Dc0gK0CvJ8ZkegFIgYBL3GAOlHszWcS9T/CA9d0BpCi591l4/36PeIhhY4KAuRh6trUqJV2oMIB3LgA==,iv:NMGHF47iAQGzLSKsBAWVPN3khl/FE+Y+EIO/xTZu+1w=,tag:SKlbhtqfd3TplMonE6+ElQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:sk3ytSzx2dPYUS893ZaU9bW/8dwjDvj0E9EpebQOpxDyGd0MhQSCUMOlACKmfxqTV47fI62dgKzDe5adI9o8mZAbHFxOPY95R9cm/Qqx2u5xb785Xg1F0Sejuq13hQBcUBxdn0Ju5sjaCo7Zu9eCJ5w3sWYsA8mEhF2oXKj8i1C9Io8sjYyM70MszalC+ygSkKfUvhru6oruHTKg+hl7TWurOdX+eWFHpi92,iv:3TrpUJ4MLEP7QkQyIioMV5MjGhuhmjo5rZJxOXhSS3E=,tag:erOJ4PaCtSD9WQvSz50Y/Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dh500hvzwf3pzyk3hmye4580nn8dme6tu5mtjag5kr45ad5cw3jq04uw5a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK09LOG4zeWdTWFJkNkV5
            WFR4WVFuWFBhRmNvdGFoSFhLVnJydnE2cmhBCkRSVzkzUXNwb0o1L1JJWmI0Y3ZK
            cEwweXJxaFIxcUN3cG44b3ZGMDVIa2cKLS0tIFZuYXp4Qy9Sc3BoY2xkTzgxeG9q
            Wk5IVTFZamp2NWp5dktsbWJDellHencK1ab2brzM5EX3CA56LUn9YFhSYpu2Rw5K
            nNxfWKKlfGY+25OXR/ZM+s8Pz+UibclCDq99ZVnpeOVBsPoqY1yj1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-27T21:03:40Z"
    mac: ENC[AES256_GCM,data:IMFpSuHSG0eSk9Zu6WMrwbEPsBpQzzwOGqaWcqBAUFF44GHS+r/WBddephRq3Ji6Cpt2KyBKfX0mzFDnEc5el60yMBGl4m4Wp9lUuVTBfLvCDJ/3yNcPMiUJ3R0S5UL7CPVrefg/On0E0Yj+Ro6Nj7hl71jy+8LNspVTv3Vwhhg=,iv:ysouaGr0kIlWHq6ulSf7deClh2bKUt9NUW50WRMeQ40=,tag:ME5iS8kToxeAdXTcDuPPmg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
